# Generated by Django 4.2.1 on 2023-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', max_length=2)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=300)),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restricted Item')),
            ],
        ),
    ]
